<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net472</TargetFramework><AssemblyName>Fixture.Managed.Provider</AssemblyName><AssemblyVersion>1.0.0.0</AssemblyVersion><LangVersion>7.3</LangVersion></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../../Dependencies/Phinix.Common/Common/Utils/Utils.csproj" /></ItemGroup>
</Project>
