<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Phinix.Example.Basic</AssemblyName>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <PhinixRoot Condition="'$(PhinixRoot)' == ''">$(MSBuildThisFileDirectory)../../../..</PhinixRoot>
    <GameReferences Condition="'$(GameReferences)' == '' and Exists('$(PhinixRoot)/GameDlls/1.6')">$(PhinixRoot)/GameDlls/1.6</GameReferences>
    <GameReferences Condition="'$(GameReferences)' == ''">$(PhinixRoot)/GameDlls</GameReferences>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ExampleExtension.cs" />
    <ProjectReference Include="$(PhinixRoot)/Client/ClientExtensionAbstractions/ClientExtensionAbstractions.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="$(PhinixRoot)/Common/Utils/Utils.csproj"><Private>false</Private><SetTargetFramework>TargetFramework=net472</SetTargetFramework></ProjectReference>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameReferences)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameReferences)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(GameReferences)/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameReferences)/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
