// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Shared/FrameworkShared.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Phinix.Framework {

  /// <summary>Holder for reflection information generated from Shared/FrameworkShared.proto</summary>
  public static partial class FrameworkSharedReflection {

    #region Descriptor
    /// <summary>File descriptor for Shared/FrameworkShared.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameworkSharedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxTaGFyZWQvRnJhbWV3b3JrU2hhcmVkLnByb3RvEhBQaGluaXguRnJhbWV3",
            "b3JrGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIjQKFkZyYW1l",
            "d29ya01ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJ",
            "IpMCCg9GcmFtZXdvcmtIZWFkZXISGQoRZnJhbWV3b3JrX3ZlcnNpb24YASAB",
            "KA0SLQoEZmxvdxgCIAEoDjIfLlBoaW5peC5GcmFtZXdvcmsuRnJhbWV3b3Jr",
            "RmxvdxIPCgd0eXBlX2lkGAMgASgJEhEKCXBhY2tldF9pZBgEIAEoCRISCgpz",
            "ZXNzaW9uX2lkGAUgASgJEhMKC3NlbmRlcl91dWlkGAYgASgJEi0KCXRpbWVz",
            "dGFtcBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASOgoIbWV0",
            "YWRhdGEYCCADKAsyKC5QaGluaXguRnJhbWV3b3JrLkZyYW1ld29ya01ldGFk",
            "YXRhRW50cnkqgAEKDUZyYW1ld29ya0Zsb3cSHgoaRlJBTUVXT1JLX0ZMT1df",
            "VU5TUEVDSUZJRUQQABIaChZGUkFNRVdPUktfRkxPV19NRVNTQUdFEAESGgoW",
            "RlJBTUVXT1JLX0ZMT1dfQ09NTUFORBACEhcKE0ZSQU1FV09SS19GTE9XX0lU",
            "RU0QA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Phinix.Framework.FrameworkFlow), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.FrameworkMetadataEntry), global::Phinix.Framework.FrameworkMetadataEntry.Parser, new[]{ "Key", "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.FrameworkHeader), global::Phinix.Framework.FrameworkHeader.Parser, new[]{ "FrameworkVersion", "Flow", "TypeId", "PacketId", "SessionId", "SenderUuid", "Timestamp", "Metadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FrameworkFlow {
    [pbr::OriginalName("FRAMEWORK_FLOW_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("FRAMEWORK_FLOW_MESSAGE")] Message = 1,
    [pbr::OriginalName("FRAMEWORK_FLOW_COMMAND")] Command = 2,
    [pbr::OriginalName("FRAMEWORK_FLOW_ITEM")] Item = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkMetadataEntry : pb::IMessage<FrameworkMetadataEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkMetadataEntry> _parser = new pb::MessageParser<FrameworkMetadataEntry>(() => new FrameworkMetadataEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkMetadataEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.FrameworkSharedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkMetadataEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkMetadataEntry(FrameworkMetadataEntry other) : this() {
      key_ = other.key_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkMetadataEntry Clone() {
      return new FrameworkMetadataEntry(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkMetadataEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkMetadataEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkMetadataEntry other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkHeader : pb::IMessage<FrameworkHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkHeader> _parser = new pb::MessageParser<FrameworkHeader>(() => new FrameworkHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.FrameworkSharedReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkHeader(FrameworkHeader other) : this() {
      frameworkVersion_ = other.frameworkVersion_;
      flow_ = other.flow_;
      typeId_ = other.typeId_;
      packetId_ = other.packetId_;
      sessionId_ = other.sessionId_;
      senderUuid_ = other.senderUuid_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      metadata_ = other.metadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkHeader Clone() {
      return new FrameworkHeader(this);
    }

    /// <summary>Field number for the "framework_version" field.</summary>
    public const int FrameworkVersionFieldNumber = 1;
    private uint frameworkVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameworkVersion {
      get { return frameworkVersion_; }
      set {
        frameworkVersion_ = value;
      }
    }

    /// <summary>Field number for the "flow" field.</summary>
    public const int FlowFieldNumber = 2;
    private global::Phinix.Framework.FrameworkFlow flow_ = global::Phinix.Framework.FrameworkFlow.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Phinix.Framework.FrameworkFlow Flow {
      get { return flow_; }
      set {
        flow_ = value;
      }
    }

    /// <summary>Field number for the "type_id" field.</summary>
    public const int TypeIdFieldNumber = 3;
    private string typeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TypeId {
      get { return typeId_; }
      set {
        typeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "packet_id" field.</summary>
    public const int PacketIdFieldNumber = 4;
    private string packetId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PacketId {
      get { return packetId_; }
      set {
        packetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 5;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sender_uuid" field.</summary>
    public const int SenderUuidFieldNumber = 6;
    private string senderUuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderUuid {
      get { return senderUuid_; }
      set {
        senderUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Phinix.Framework.FrameworkMetadataEntry> _repeated_metadata_codec
        = pb::FieldCodec.ForMessage(66, global::Phinix.Framework.FrameworkMetadataEntry.Parser);
    private readonly pbc::RepeatedField<global::Phinix.Framework.FrameworkMetadataEntry> metadata_ = new pbc::RepeatedField<global::Phinix.Framework.FrameworkMetadataEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Phinix.Framework.FrameworkMetadataEntry> Metadata {
      get { return metadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameworkVersion != other.FrameworkVersion) return false;
      if (Flow != other.Flow) return false;
      if (TypeId != other.TypeId) return false;
      if (PacketId != other.PacketId) return false;
      if (SessionId != other.SessionId) return false;
      if (SenderUuid != other.SenderUuid) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if(!metadata_.Equals(other.metadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameworkVersion != 0) hash ^= FrameworkVersion.GetHashCode();
      if (Flow != global::Phinix.Framework.FrameworkFlow.Unspecified) hash ^= Flow.GetHashCode();
      if (TypeId.Length != 0) hash ^= TypeId.GetHashCode();
      if (PacketId.Length != 0) hash ^= PacketId.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (SenderUuid.Length != 0) hash ^= SenderUuid.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      hash ^= metadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrameworkVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameworkVersion);
      }
      if (Flow != global::Phinix.Framework.FrameworkFlow.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Flow);
      }
      if (TypeId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TypeId);
      }
      if (PacketId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PacketId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SessionId);
      }
      if (SenderUuid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderUuid);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Timestamp);
      }
      metadata_.WriteTo(output, _repeated_metadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrameworkVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameworkVersion);
      }
      if (Flow != global::Phinix.Framework.FrameworkFlow.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Flow);
      }
      if (TypeId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TypeId);
      }
      if (PacketId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PacketId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SessionId);
      }
      if (SenderUuid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderUuid);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Timestamp);
      }
      metadata_.WriteTo(ref output, _repeated_metadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrameworkVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameworkVersion);
      }
      if (Flow != global::Phinix.Framework.FrameworkFlow.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Flow);
      }
      if (TypeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TypeId);
      }
      if (PacketId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PacketId);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (SenderUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderUuid);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      size += metadata_.CalculateSize(_repeated_metadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkHeader other) {
      if (other == null) {
        return;
      }
      if (other.FrameworkVersion != 0) {
        FrameworkVersion = other.FrameworkVersion;
      }
      if (other.Flow != global::Phinix.Framework.FrameworkFlow.Unspecified) {
        Flow = other.Flow;
      }
      if (other.TypeId.Length != 0) {
        TypeId = other.TypeId;
      }
      if (other.PacketId.Length != 0) {
        PacketId = other.PacketId;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.SenderUuid.Length != 0) {
        SenderUuid = other.SenderUuid;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      metadata_.Add(other.metadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameworkVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            Flow = (global::Phinix.Framework.FrameworkFlow) input.ReadEnum();
            break;
          }
          case 26: {
            TypeId = input.ReadString();
            break;
          }
          case 34: {
            PacketId = input.ReadString();
            break;
          }
          case 42: {
            SessionId = input.ReadString();
            break;
          }
          case 50: {
            SenderUuid = input.ReadString();
            break;
          }
          case 58: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 66: {
            metadata_.AddEntriesFrom(input, _repeated_metadata_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FrameworkVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            Flow = (global::Phinix.Framework.FrameworkFlow) input.ReadEnum();
            break;
          }
          case 26: {
            TypeId = input.ReadString();
            break;
          }
          case 34: {
            PacketId = input.ReadString();
            break;
          }
          case 42: {
            SessionId = input.ReadString();
            break;
          }
          case 50: {
            SenderUuid = input.ReadString();
            break;
          }
          case 58: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 66: {
            metadata_.AddEntriesFrom(ref input, _repeated_metadata_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
