<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <OutputType>Exe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <AssemblyName>LegacyTradeRuntimeTests</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="netstandard">
      <HintPath Condition="Exists('$(FrameworkPathOverride)/Facades/netstandard.dll')">$(FrameworkPathOverride)/Facades/netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>..\..\.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Compile Include="Program.cs" />
    <ProjectReference Include="..\..\Client\Composition\Phinix.ClientComposition.csproj" />
    <ProjectReference Include="..\..\Extensions\Trade\Client\TradeExtension.Client.csproj" />
    <ProjectReference Include="..\..\Extensions\LegacyAdapter\Client\PhinixLegacyAdapter.Client.csproj" />
    <ProjectReference Include="..\..\Extensions\Trade\Contracts\TradeExtension.csproj" />
    <ProjectReference Include="..\..\Client\ClientExtensionAbstractions\ClientExtensionAbstractions.csproj" />
    <ProjectReference Include="../../Dependencies/Phinix.Common/Common/UserManagement/UserManagement.csproj" />
    <ProjectReference Include="../../Dependencies/Phinix.Common/Common/Utils/Utils.csproj" />
    <ProjectReference Include="../../Dependencies/Phinix.Common/Common/Connections/Connections.csproj" />
    <ProjectReference Include="../../Dependencies/Phinix.Common/Dependencies/protobuf/csharp/src/Google.Protobuf/Google.Protobuf.csproj" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Target Name="CopyCompositionRuntime" AfterTargets="Build">
    <ItemGroup>
      <CompositionRuntime Include="..\..\Client\Composition\bin\$(Configuration)\net472\Autofac.dll;..\..\Client\Composition\bin\$(Configuration)\net472\Microsoft.Bcl.AsyncInterfaces.dll;..\..\Client\Composition\bin\$(Configuration)\net472\System.*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(CompositionRuntime)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>
</Project>
