// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Item/FrameworkItemPacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Phinix.Framework {

  /// <summary>Holder for reflection information generated from Item/FrameworkItemPacket.proto</summary>
  public static partial class FrameworkItemPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Item/FrameworkItemPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameworkItemPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5JdGVtL0ZyYW1ld29ya0l0ZW1QYWNrZXQucHJvdG8SEFBoaW5peC5GcmFt",
            "ZXdvcmsaHFNoYXJlZC9GcmFtZXdvcmtTaGFyZWQucHJvdG8icQoTRnJhbWV3",
            "b3JrSXRlbVBhY2tldBIxCgZoZWFkZXIYASABKAsyIS5QaGluaXguRnJhbWV3",
            "b3JrLkZyYW1ld29ya0hlYWRlchIQCghjb2RlY19pZBgCIAEoCRIVCg1wYXls",
            "b2FkX2J5dGVzGAMgASgMIuYBChhGcmFtZXdvcmtWYW5pbGxhSXRlbURhdGES",
            "EAoIZGVmX25hbWUYASABKAkSEwoLc3RhY2tfY291bnQYAiABKAUSFgoOc3R1",
            "ZmZfZGVmX25hbWUYAyABKAkSNwoHcXVhbGl0eRgEIAEoDjImLlBoaW5peC5G",
            "cmFtZXdvcmsuRnJhbWV3b3JrSXRlbVF1YWxpdHkSEgoKaGl0X3BvaW50cxgF",
            "IAEoBRI+Cgppbm5lcl9pdGVtGAYgASgLMiouUGhpbml4LkZyYW1ld29yay5G",
            "cmFtZXdvcmtWYW5pbGxhSXRlbURhdGEiTwoXRnJhbWV3b3JrSXRlbUNvbGxl",
            "Y3Rpb24SNAoFaXRlbXMYASADKAsyJS5QaGluaXguRnJhbWV3b3JrLkZyYW1l",
            "d29ya0l0ZW1QYWNrZXQq2QIKFEZyYW1ld29ya0l0ZW1RdWFsaXR5EiYKIkZS",
            "QU1FV09SS19JVEVNX1FVQUxJVFlfVU5TUEVDSUZJRUQQABIgChxGUkFNRVdP",
            "UktfSVRFTV9RVUFMSVRZX0FXRlVMEAESHwobRlJBTUVXT1JLX0lURU1fUVVB",
            "TElUWV9QT09SEAISIQodRlJBTUVXT1JLX0lURU1fUVVBTElUWV9OT1JNQUwQ",
            "AxIfChtGUkFNRVdPUktfSVRFTV9RVUFMSVRZX0dPT0QQBBIkCiBGUkFNRVdP",
            "UktfSVRFTV9RVUFMSVRZX0VYQ0VMTEVOVBAFEiUKIUZSQU1FV09SS19JVEVN",
            "X1FVQUxJVFlfTUFTVEVSV09SSxAGEiQKIEZSQU1FV09SS19JVEVNX1FVQUxJ",
            "VFlfTEVHRU5EQVJZEAcSHwobRlJBTUVXT1JLX0lURU1fUVVBTElUWV9OT05F",
            "EAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Phinix.Framework.FrameworkSharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Phinix.Framework.FrameworkItemQuality), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.FrameworkItemPacket), global::Phinix.Framework.FrameworkItemPacket.Parser, new[]{ "Header", "CodecId", "PayloadBytes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.FrameworkVanillaItemData), global::Phinix.Framework.FrameworkVanillaItemData.Parser, new[]{ "DefName", "StackCount", "StuffDefName", "Quality", "HitPoints", "InnerItem" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.FrameworkItemCollection), global::Phinix.Framework.FrameworkItemCollection.Parser, new[]{ "Items" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FrameworkItemQuality {
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_AWFUL")] Awful = 1,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_POOR")] Poor = 2,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_NORMAL")] Normal = 3,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_GOOD")] Good = 4,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_EXCELLENT")] Excellent = 5,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_MASTERWORK")] Masterwork = 6,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_LEGENDARY")] Legendary = 7,
    [pbr::OriginalName("FRAMEWORK_ITEM_QUALITY_NONE")] None = 8,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkItemPacket : pb::IMessage<FrameworkItemPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkItemPacket> _parser = new pb::MessageParser<FrameworkItemPacket>(() => new FrameworkItemPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkItemPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.FrameworkItemPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkItemPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkItemPacket(FrameworkItemPacket other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      codecId_ = other.codecId_;
      payloadBytes_ = other.payloadBytes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkItemPacket Clone() {
      return new FrameworkItemPacket(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Phinix.Framework.FrameworkHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Phinix.Framework.FrameworkHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "codec_id" field.</summary>
    public const int CodecIdFieldNumber = 2;
    private string codecId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CodecId {
      get { return codecId_; }
      set {
        codecId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload_bytes" field.</summary>
    public const int PayloadBytesFieldNumber = 3;
    private pb::ByteString payloadBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PayloadBytes {
      get { return payloadBytes_; }
      set {
        payloadBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkItemPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkItemPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (CodecId != other.CodecId) return false;
      if (PayloadBytes != other.PayloadBytes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (CodecId.Length != 0) hash ^= CodecId.GetHashCode();
      if (PayloadBytes.Length != 0) hash ^= PayloadBytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (CodecId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CodecId);
      }
      if (PayloadBytes.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PayloadBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (CodecId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CodecId);
      }
      if (PayloadBytes.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PayloadBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (CodecId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodecId);
      }
      if (PayloadBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PayloadBytes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkItemPacket other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Phinix.Framework.FrameworkHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.CodecId.Length != 0) {
        CodecId = other.CodecId;
      }
      if (other.PayloadBytes.Length != 0) {
        PayloadBytes = other.PayloadBytes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Phinix.Framework.FrameworkHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            CodecId = input.ReadString();
            break;
          }
          case 26: {
            PayloadBytes = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Phinix.Framework.FrameworkHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            CodecId = input.ReadString();
            break;
          }
          case 26: {
            PayloadBytes = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkVanillaItemData : pb::IMessage<FrameworkVanillaItemData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkVanillaItemData> _parser = new pb::MessageParser<FrameworkVanillaItemData>(() => new FrameworkVanillaItemData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkVanillaItemData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.FrameworkItemPacketReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkVanillaItemData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkVanillaItemData(FrameworkVanillaItemData other) : this() {
      defName_ = other.defName_;
      stackCount_ = other.stackCount_;
      stuffDefName_ = other.stuffDefName_;
      quality_ = other.quality_;
      hitPoints_ = other.hitPoints_;
      innerItem_ = other.innerItem_ != null ? other.innerItem_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkVanillaItemData Clone() {
      return new FrameworkVanillaItemData(this);
    }

    /// <summary>Field number for the "def_name" field.</summary>
    public const int DefNameFieldNumber = 1;
    private string defName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefName {
      get { return defName_; }
      set {
        defName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stack_count" field.</summary>
    public const int StackCountFieldNumber = 2;
    private int stackCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StackCount {
      get { return stackCount_; }
      set {
        stackCount_ = value;
      }
    }

    /// <summary>Field number for the "stuff_def_name" field.</summary>
    public const int StuffDefNameFieldNumber = 3;
    private string stuffDefName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StuffDefName {
      get { return stuffDefName_; }
      set {
        stuffDefName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quality" field.</summary>
    public const int QualityFieldNumber = 4;
    private global::Phinix.Framework.FrameworkItemQuality quality_ = global::Phinix.Framework.FrameworkItemQuality.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Phinix.Framework.FrameworkItemQuality Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "hit_points" field.</summary>
    public const int HitPointsFieldNumber = 5;
    private int hitPoints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HitPoints {
      get { return hitPoints_; }
      set {
        hitPoints_ = value;
      }
    }

    /// <summary>Field number for the "inner_item" field.</summary>
    public const int InnerItemFieldNumber = 6;
    private global::Phinix.Framework.FrameworkVanillaItemData innerItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Phinix.Framework.FrameworkVanillaItemData InnerItem {
      get { return innerItem_; }
      set {
        innerItem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkVanillaItemData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkVanillaItemData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DefName != other.DefName) return false;
      if (StackCount != other.StackCount) return false;
      if (StuffDefName != other.StuffDefName) return false;
      if (Quality != other.Quality) return false;
      if (HitPoints != other.HitPoints) return false;
      if (!object.Equals(InnerItem, other.InnerItem)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DefName.Length != 0) hash ^= DefName.GetHashCode();
      if (StackCount != 0) hash ^= StackCount.GetHashCode();
      if (StuffDefName.Length != 0) hash ^= StuffDefName.GetHashCode();
      if (Quality != global::Phinix.Framework.FrameworkItemQuality.Unspecified) hash ^= Quality.GetHashCode();
      if (HitPoints != 0) hash ^= HitPoints.GetHashCode();
      if (innerItem_ != null) hash ^= InnerItem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DefName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DefName);
      }
      if (StackCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StackCount);
      }
      if (StuffDefName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StuffDefName);
      }
      if (Quality != global::Phinix.Framework.FrameworkItemQuality.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Quality);
      }
      if (HitPoints != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(HitPoints);
      }
      if (innerItem_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(InnerItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DefName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DefName);
      }
      if (StackCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StackCount);
      }
      if (StuffDefName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StuffDefName);
      }
      if (Quality != global::Phinix.Framework.FrameworkItemQuality.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Quality);
      }
      if (HitPoints != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(HitPoints);
      }
      if (innerItem_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(InnerItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DefName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefName);
      }
      if (StackCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StackCount);
      }
      if (StuffDefName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StuffDefName);
      }
      if (Quality != global::Phinix.Framework.FrameworkItemQuality.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Quality);
      }
      if (HitPoints != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HitPoints);
      }
      if (innerItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InnerItem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkVanillaItemData other) {
      if (other == null) {
        return;
      }
      if (other.DefName.Length != 0) {
        DefName = other.DefName;
      }
      if (other.StackCount != 0) {
        StackCount = other.StackCount;
      }
      if (other.StuffDefName.Length != 0) {
        StuffDefName = other.StuffDefName;
      }
      if (other.Quality != global::Phinix.Framework.FrameworkItemQuality.Unspecified) {
        Quality = other.Quality;
      }
      if (other.HitPoints != 0) {
        HitPoints = other.HitPoints;
      }
      if (other.innerItem_ != null) {
        if (innerItem_ == null) {
          InnerItem = new global::Phinix.Framework.FrameworkVanillaItemData();
        }
        InnerItem.MergeFrom(other.InnerItem);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DefName = input.ReadString();
            break;
          }
          case 16: {
            StackCount = input.ReadInt32();
            break;
          }
          case 26: {
            StuffDefName = input.ReadString();
            break;
          }
          case 32: {
            Quality = (global::Phinix.Framework.FrameworkItemQuality) input.ReadEnum();
            break;
          }
          case 40: {
            HitPoints = input.ReadInt32();
            break;
          }
          case 50: {
            if (innerItem_ == null) {
              InnerItem = new global::Phinix.Framework.FrameworkVanillaItemData();
            }
            input.ReadMessage(InnerItem);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DefName = input.ReadString();
            break;
          }
          case 16: {
            StackCount = input.ReadInt32();
            break;
          }
          case 26: {
            StuffDefName = input.ReadString();
            break;
          }
          case 32: {
            Quality = (global::Phinix.Framework.FrameworkItemQuality) input.ReadEnum();
            break;
          }
          case 40: {
            HitPoints = input.ReadInt32();
            break;
          }
          case 50: {
            if (innerItem_ == null) {
              InnerItem = new global::Phinix.Framework.FrameworkVanillaItemData();
            }
            input.ReadMessage(InnerItem);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkItemCollection : pb::IMessage<FrameworkItemCollection>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkItemCollection> _parser = new pb::MessageParser<FrameworkItemCollection>(() => new FrameworkItemCollection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkItemCollection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.FrameworkItemPacketReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkItemCollection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkItemCollection(FrameworkItemCollection other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkItemCollection Clone() {
      return new FrameworkItemCollection(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phinix.Framework.FrameworkItemPacket> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Phinix.Framework.FrameworkItemPacket.Parser);
    private readonly pbc::RepeatedField<global::Phinix.Framework.FrameworkItemPacket> items_ = new pbc::RepeatedField<global::Phinix.Framework.FrameworkItemPacket>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Phinix.Framework.FrameworkItemPacket> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkItemCollection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkItemCollection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkItemCollection other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
