// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message/BuiltInChat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Phinix.Framework {

  /// <summary>Holder for reflection information generated from Message/BuiltInChat.proto</summary>
  public static partial class BuiltInChatReflection {

    #region Descriptor
    /// <summary>File descriptor for Message/BuiltInChat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuiltInChatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlNZXNzYWdlL0J1aWx0SW5DaGF0LnByb3RvEhBQaGluaXguRnJhbWV3b3Jr",
            "Gh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIogCChlCdWlsdElu",
            "Q2hhdE1lc3NhZ2VQYXlsb2FkEhIKCm1lc3NhZ2VfaWQYASABKAkSEwoLc2Vu",
            "ZGVyX3V1aWQYAiABKAkSDwoHbWVzc2FnZRgDIAEoCRItCgl0aW1lc3RhbXAY",
            "BCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhcKD21lbnRpb25l",
            "ZF91dWlkcxgFIAMoCRIbChNyZXBseV90b19tZXNzYWdlX2lkGAYgASgJEhgK",
            "EHJlcGx5X3RvX3NuaXBwZXQYByABKAkSEQoJaXNfbm90aWNlGAggASgIEh8K",
            "F25vdGljZV9kdXJhdGlvbl9zZWNvbmRzGAkgASgFIl0KF0J1aWx0SW5DaGF0",
            "SGlzdG9yeVN0b3JlEkIKDWNoYXRfbWVzc2FnZXMYASADKAsyKy5QaGluaXgu",
            "RnJhbWV3b3JrLkJ1aWx0SW5DaGF0TWVzc2FnZVBheWxvYWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.BuiltInChatMessagePayload), global::Phinix.Framework.BuiltInChatMessagePayload.Parser, new[]{ "MessageId", "SenderUuid", "Message", "Timestamp", "MentionedUuids", "ReplyToMessageId", "ReplyToSnippet", "IsNotice", "NoticeDurationSeconds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.BuiltInChatHistoryStore), global::Phinix.Framework.BuiltInChatHistoryStore.Parser, new[]{ "ChatMessages" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BuiltInChatMessagePayload : pb::IMessage<BuiltInChatMessagePayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BuiltInChatMessagePayload> _parser = new pb::MessageParser<BuiltInChatMessagePayload>(() => new BuiltInChatMessagePayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BuiltInChatMessagePayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.BuiltInChatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuiltInChatMessagePayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuiltInChatMessagePayload(BuiltInChatMessagePayload other) : this() {
      messageId_ = other.messageId_;
      senderUuid_ = other.senderUuid_;
      message_ = other.message_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      mentionedUuids_ = other.mentionedUuids_.Clone();
      replyToMessageId_ = other.replyToMessageId_;
      replyToSnippet_ = other.replyToSnippet_;
      isNotice_ = other.isNotice_;
      noticeDurationSeconds_ = other.noticeDurationSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuiltInChatMessagePayload Clone() {
      return new BuiltInChatMessagePayload(this);
    }

    /// <summary>Field number for the "message_id" field.</summary>
    public const int MessageIdFieldNumber = 1;
    private string messageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageId {
      get { return messageId_; }
      set {
        messageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sender_uuid" field.</summary>
    public const int SenderUuidFieldNumber = 2;
    private string senderUuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderUuid {
      get { return senderUuid_; }
      set {
        senderUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "mentioned_uuids" field.</summary>
    public const int MentionedUuidsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_mentionedUuids_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> mentionedUuids_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> MentionedUuids {
      get { return mentionedUuids_; }
    }

    /// <summary>Field number for the "reply_to_message_id" field.</summary>
    public const int ReplyToMessageIdFieldNumber = 6;
    private string replyToMessageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReplyToMessageId {
      get { return replyToMessageId_; }
      set {
        replyToMessageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reply_to_snippet" field.</summary>
    public const int ReplyToSnippetFieldNumber = 7;
    private string replyToSnippet_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReplyToSnippet {
      get { return replyToSnippet_; }
      set {
        replyToSnippet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_notice" field.</summary>
    public const int IsNoticeFieldNumber = 8;
    private bool isNotice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNotice {
      get { return isNotice_; }
      set {
        isNotice_ = value;
      }
    }

    /// <summary>Field number for the "notice_duration_seconds" field.</summary>
    public const int NoticeDurationSecondsFieldNumber = 9;
    private int noticeDurationSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NoticeDurationSeconds {
      get { return noticeDurationSeconds_; }
      set {
        noticeDurationSeconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BuiltInChatMessagePayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BuiltInChatMessagePayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageId != other.MessageId) return false;
      if (SenderUuid != other.SenderUuid) return false;
      if (Message != other.Message) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if(!mentionedUuids_.Equals(other.mentionedUuids_)) return false;
      if (ReplyToMessageId != other.ReplyToMessageId) return false;
      if (ReplyToSnippet != other.ReplyToSnippet) return false;
      if (IsNotice != other.IsNotice) return false;
      if (NoticeDurationSeconds != other.NoticeDurationSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageId.Length != 0) hash ^= MessageId.GetHashCode();
      if (SenderUuid.Length != 0) hash ^= SenderUuid.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      hash ^= mentionedUuids_.GetHashCode();
      if (ReplyToMessageId.Length != 0) hash ^= ReplyToMessageId.GetHashCode();
      if (ReplyToSnippet.Length != 0) hash ^= ReplyToSnippet.GetHashCode();
      if (IsNotice != false) hash ^= IsNotice.GetHashCode();
      if (NoticeDurationSeconds != 0) hash ^= NoticeDurationSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageId);
      }
      if (SenderUuid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SenderUuid);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Timestamp);
      }
      mentionedUuids_.WriteTo(output, _repeated_mentionedUuids_codec);
      if (ReplyToMessageId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ReplyToMessageId);
      }
      if (ReplyToSnippet.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ReplyToSnippet);
      }
      if (IsNotice != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsNotice);
      }
      if (NoticeDurationSeconds != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(NoticeDurationSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageId);
      }
      if (SenderUuid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SenderUuid);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Timestamp);
      }
      mentionedUuids_.WriteTo(ref output, _repeated_mentionedUuids_codec);
      if (ReplyToMessageId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ReplyToMessageId);
      }
      if (ReplyToSnippet.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ReplyToSnippet);
      }
      if (IsNotice != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsNotice);
      }
      if (NoticeDurationSeconds != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(NoticeDurationSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageId);
      }
      if (SenderUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderUuid);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      size += mentionedUuids_.CalculateSize(_repeated_mentionedUuids_codec);
      if (ReplyToMessageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReplyToMessageId);
      }
      if (ReplyToSnippet.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReplyToSnippet);
      }
      if (IsNotice != false) {
        size += 1 + 1;
      }
      if (NoticeDurationSeconds != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoticeDurationSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BuiltInChatMessagePayload other) {
      if (other == null) {
        return;
      }
      if (other.MessageId.Length != 0) {
        MessageId = other.MessageId;
      }
      if (other.SenderUuid.Length != 0) {
        SenderUuid = other.SenderUuid;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      mentionedUuids_.Add(other.mentionedUuids_);
      if (other.ReplyToMessageId.Length != 0) {
        ReplyToMessageId = other.ReplyToMessageId;
      }
      if (other.ReplyToSnippet.Length != 0) {
        ReplyToSnippet = other.ReplyToSnippet;
      }
      if (other.IsNotice != false) {
        IsNotice = other.IsNotice;
      }
      if (other.NoticeDurationSeconds != 0) {
        NoticeDurationSeconds = other.NoticeDurationSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MessageId = input.ReadString();
            break;
          }
          case 18: {
            SenderUuid = input.ReadString();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
          case 34: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 42: {
            mentionedUuids_.AddEntriesFrom(input, _repeated_mentionedUuids_codec);
            break;
          }
          case 50: {
            ReplyToMessageId = input.ReadString();
            break;
          }
          case 58: {
            ReplyToSnippet = input.ReadString();
            break;
          }
          case 64: {
            IsNotice = input.ReadBool();
            break;
          }
          case 72: {
            NoticeDurationSeconds = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MessageId = input.ReadString();
            break;
          }
          case 18: {
            SenderUuid = input.ReadString();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
          case 34: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 42: {
            mentionedUuids_.AddEntriesFrom(ref input, _repeated_mentionedUuids_codec);
            break;
          }
          case 50: {
            ReplyToMessageId = input.ReadString();
            break;
          }
          case 58: {
            ReplyToSnippet = input.ReadString();
            break;
          }
          case 64: {
            IsNotice = input.ReadBool();
            break;
          }
          case 72: {
            NoticeDurationSeconds = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BuiltInChatHistoryStore : pb::IMessage<BuiltInChatHistoryStore>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BuiltInChatHistoryStore> _parser = new pb::MessageParser<BuiltInChatHistoryStore>(() => new BuiltInChatHistoryStore());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BuiltInChatHistoryStore> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.BuiltInChatReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuiltInChatHistoryStore() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuiltInChatHistoryStore(BuiltInChatHistoryStore other) : this() {
      chatMessages_ = other.chatMessages_.Clone();
      notices_ = other.notices_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuiltInChatHistoryStore Clone() {
      return new BuiltInChatHistoryStore(this);
    }

    /// <summary>Field number for the "chat_messages" field.</summary>
    public const int ChatMessagesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phinix.Framework.BuiltInChatMessagePayload> _repeated_chatMessages_codec
        = pb::FieldCodec.ForMessage(10, global::Phinix.Framework.BuiltInChatMessagePayload.Parser);
    private readonly pbc::RepeatedField<global::Phinix.Framework.BuiltInChatMessagePayload> chatMessages_ = new pbc::RepeatedField<global::Phinix.Framework.BuiltInChatMessagePayload>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Phinix.Framework.BuiltInChatMessagePayload> ChatMessages {
      get { return chatMessages_; }
    }

    /// <summary>Field number for the "notices" field.</summary>
    public const int NoticesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Phinix.Framework.BuiltInChatMessagePayload> _repeated_notices_codec
        = pb::FieldCodec.ForMessage(18, global::Phinix.Framework.BuiltInChatMessagePayload.Parser);
    private readonly pbc::RepeatedField<global::Phinix.Framework.BuiltInChatMessagePayload> notices_ = new pbc::RepeatedField<global::Phinix.Framework.BuiltInChatMessagePayload>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Phinix.Framework.BuiltInChatMessagePayload> Notices {
      get { return notices_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BuiltInChatHistoryStore);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BuiltInChatHistoryStore other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!chatMessages_.Equals(other.chatMessages_)) return false;
      if(!notices_.Equals(other.notices_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= chatMessages_.GetHashCode();
      hash ^= notices_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      chatMessages_.WriteTo(output, _repeated_chatMessages_codec);
      notices_.WriteTo(output, _repeated_notices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      chatMessages_.WriteTo(ref output, _repeated_chatMessages_codec);
      notices_.WriteTo(ref output, _repeated_notices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += chatMessages_.CalculateSize(_repeated_chatMessages_codec);
      size += notices_.CalculateSize(_repeated_notices_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BuiltInChatHistoryStore other) {
      if (other == null) {
        return;
      }
      chatMessages_.Add(other.chatMessages_);
      notices_.Add(other.notices_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            chatMessages_.AddEntriesFrom(input, _repeated_chatMessages_codec);
            break;
          }
          case 18: {
            notices_.AddEntriesFrom(input, _repeated_notices_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            chatMessages_.AddEntriesFrom(ref input, _repeated_chatMessages_codec);
            break;
          }
          case 18: {
            notices_.AddEntriesFrom(ref input, _repeated_notices_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
