// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Command/FrameworkCommandPacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Phinix.Framework {

  /// <summary>Holder for reflection information generated from Command/FrameworkCommandPacket.proto</summary>
  public static partial class FrameworkCommandPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Command/FrameworkCommandPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameworkCommandPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRDb21tYW5kL0ZyYW1ld29ya0NvbW1hbmRQYWNrZXQucHJvdG8SEFBoaW5p",
            "eC5GcmFtZXdvcmsaHFNoYXJlZC9GcmFtZXdvcmtTaGFyZWQucHJvdG8ioAEK",
            "FkZyYW1ld29ya0NvbW1hbmRQYWNrZXQSMQoGaGVhZGVyGAEgASgLMiEuUGhp",
            "bml4LkZyYW1ld29yay5GcmFtZXdvcmtIZWFkZXISPAoMY29tbWFuZF9raW5k",
            "GAIgASgOMiYuUGhpbml4LkZyYW1ld29yay5GcmFtZXdvcmtDb21tYW5kS2lu",
            "ZBIVCg1wYXlsb2FkX2J5dGVzGAMgASgMKssBChRGcmFtZXdvcmtDb21tYW5k",
            "S2luZBImCiJGUkFNRVdPUktfQ09NTUFORF9LSU5EX1VOU1BFQ0lGSUVEEAAS",
            "IgoeRlJBTUVXT1JLX0NPTU1BTkRfS0lORF9SRVFVRVNUEAESIwofRlJBTUVX",
            "T1JLX0NPTU1BTkRfS0lORF9SRVNQT05TRRACEiAKHEZSQU1FV09SS19DT01N",
            "QU5EX0tJTkRfU1RBVEUQAxIgChxGUkFNRVdPUktfQ09NTUFORF9LSU5EX0VW",
            "RU5UEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Phinix.Framework.FrameworkSharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Phinix.Framework.FrameworkCommandKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Phinix.Framework.FrameworkCommandPacket), global::Phinix.Framework.FrameworkCommandPacket.Parser, new[]{ "Header", "CommandKind", "PayloadBytes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FrameworkCommandKind {
    [pbr::OriginalName("FRAMEWORK_COMMAND_KIND_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("FRAMEWORK_COMMAND_KIND_REQUEST")] Request = 1,
    [pbr::OriginalName("FRAMEWORK_COMMAND_KIND_RESPONSE")] Response = 2,
    [pbr::OriginalName("FRAMEWORK_COMMAND_KIND_STATE")] State = 3,
    [pbr::OriginalName("FRAMEWORK_COMMAND_KIND_EVENT")] Event = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrameworkCommandPacket : pb::IMessage<FrameworkCommandPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameworkCommandPacket> _parser = new pb::MessageParser<FrameworkCommandPacket>(() => new FrameworkCommandPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameworkCommandPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phinix.Framework.FrameworkCommandPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkCommandPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkCommandPacket(FrameworkCommandPacket other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      commandKind_ = other.commandKind_;
      payloadBytes_ = other.payloadBytes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameworkCommandPacket Clone() {
      return new FrameworkCommandPacket(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Phinix.Framework.FrameworkHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Phinix.Framework.FrameworkHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "command_kind" field.</summary>
    public const int CommandKindFieldNumber = 2;
    private global::Phinix.Framework.FrameworkCommandKind commandKind_ = global::Phinix.Framework.FrameworkCommandKind.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Phinix.Framework.FrameworkCommandKind CommandKind {
      get { return commandKind_; }
      set {
        commandKind_ = value;
      }
    }

    /// <summary>Field number for the "payload_bytes" field.</summary>
    public const int PayloadBytesFieldNumber = 3;
    private pb::ByteString payloadBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PayloadBytes {
      get { return payloadBytes_; }
      set {
        payloadBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameworkCommandPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameworkCommandPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (CommandKind != other.CommandKind) return false;
      if (PayloadBytes != other.PayloadBytes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (CommandKind != global::Phinix.Framework.FrameworkCommandKind.Unspecified) hash ^= CommandKind.GetHashCode();
      if (PayloadBytes.Length != 0) hash ^= PayloadBytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (CommandKind != global::Phinix.Framework.FrameworkCommandKind.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) CommandKind);
      }
      if (PayloadBytes.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PayloadBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (CommandKind != global::Phinix.Framework.FrameworkCommandKind.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) CommandKind);
      }
      if (PayloadBytes.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PayloadBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (CommandKind != global::Phinix.Framework.FrameworkCommandKind.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CommandKind);
      }
      if (PayloadBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PayloadBytes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameworkCommandPacket other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Phinix.Framework.FrameworkHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.CommandKind != global::Phinix.Framework.FrameworkCommandKind.Unspecified) {
        CommandKind = other.CommandKind;
      }
      if (other.PayloadBytes.Length != 0) {
        PayloadBytes = other.PayloadBytes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Phinix.Framework.FrameworkHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            CommandKind = (global::Phinix.Framework.FrameworkCommandKind) input.ReadEnum();
            break;
          }
          case 26: {
            PayloadBytes = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Phinix.Framework.FrameworkHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            CommandKind = (global::Phinix.Framework.FrameworkCommandKind) input.ReadEnum();
            break;
          }
          case 26: {
            PayloadBytes = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
