<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Fixture.ClientAuthorEntry</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Client/ClientExtensionAbstractions/ClientExtensionAbstractions.csproj" />
  </ItemGroup>
</Project>
