<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net472</TargetFramework><LangVersion>7.3</LangVersion><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Client/Composition/Phinix.ClientComposition.csproj" />
    <ProjectReference Include="../../Extensions/Inventory/Client/InventoryExtension.Client.csproj" />
    <Reference Include="Assembly-CSharp"><HintPath>../../GameDlls/Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../GameDlls/UnityEngine.CoreModule.dll</HintPath></Reference>
  </ItemGroup>
</Project>
